<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'nuevo' => [[], ['_controller' => 'App\\Controller\\ArchivosController::index'], [], [['text', '/nuevo']], [], []],
    'analizar' => [[], ['_controller' => 'App\\Controller\\ArchivosController::analizar'], [], [['text', '/analizar']], [], []],
    'report' => [[], ['_controller' => 'App\\Controller\\ArchivosController::report'], [], [['text', '/report']], [], []],
    'editar' => [[], ['_controller' => 'App\\Controller\\ArchivosController::editar'], [], [['text', '/editar']], [], []],
    'borrar' => [[], ['_controller' => 'App\\Controller\\ArchivosController::borrar'], [], [['text', '/borrar']], [], []],
    'restaurar' => [[], ['_controller' => 'App\\Controller\\ArchivosController::restaurar'], [], [['text', '/restaurar']], [], []],
    'definitivo' => [[], ['_controller' => 'App\\Controller\\ArchivosController::borradoDefinitivo'], [], [['text', '/definitivo']], [], []],
    'comprimir' => [[], ['_controller' => 'App\\Controller\\ArchivosController::comprimir'], [], [['text', '/comprimir']], [], []],
    'compartir' => [[], ['_controller' => 'App\\Controller\\ArchivosController::compartir'], [], [['text', '/compartir']], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\IndexController::index'], [], [['text', '/']], [], []],
    'nueva_pass' => [[], ['_controller' => 'App\\Controller\\NuevaPassController::index'], [], [['text', '/nuevapass']], [], []],
    'newpass' => [[], ['_controller' => 'App\\Controller\\NuevaPassController::newPass'], [], [['text', '/newpass']], [], []],
    'panel' => [[], ['_controller' => 'App\\Controller\\PanelController::index'], [], [['text', '/panel']], [], []],
    'perfil' => [[], ['_controller' => 'App\\Controller\\PerfilController::index'], [], [['text', '/perfil']], [], []],
    'email' => [[], ['_controller' => 'App\\Controller\\PerfilController::buscarEmail'], [], [['text', '/email']], [], []],
    'c_email' => [[], ['_controller' => 'App\\Controller\\PerfilController::cambiarEmail'], [], [['text', '/c_email']], [], []],
    'usuario' => [[], ['_controller' => 'App\\Controller\\PerfilController::buscarUsuario'], [], [['text', '/usuario']], [], []],
    'c_usuario' => [[], ['_controller' => 'App\\Controller\\PerfilController::cambiarUsuario'], [], [['text', '/c_usuario']], [], []],
    'pass' => [[], ['_controller' => 'App\\Controller\\PerfilController::compruebaPass'], [], [['text', '/pass']], [], []],
    'c_pass' => [[], ['_controller' => 'App\\Controller\\PerfilController::cambiarPass'], [], [['text', '/c_pass']], [], []],
    'e_user' => [[], ['_controller' => 'App\\Controller\\PerfilController::eliminarUsuario'], [], [['text', '/e_user']], [], []],
    'registro' => [[], ['_controller' => 'App\\Controller\\RegistroController::index'], [], [['text', '/registro']], [], []],
    'reset' => [[], ['_controller' => 'App\\Controller\\ResetPasswordController::sendEmail'], [], [['text', '/reset']], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
    'fos_js_routing_js' => [['_format'], ['_controller' => 'fos_js_routing.controller::indexAction', '_format' => 'js'], ['_format' => 'js|json'], [['variable', '.', 'js|json', '_format', true], ['text', '/js/routing']], [], []],
];
