<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSMx43vJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSMx43vJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSMx43vJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSMx43vJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSMx43vJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'SMx43vJ',
    'container.build_id' => 'e9e6bedb',
    'container.build_time' => 1589896699,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSMx43vJ');
