<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOh1ikoy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOh1ikoy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOh1ikoy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOh1ikoy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOh1ikoy\App_KernelDevDebugContainer([
    'container.build_hash' => 'Oh1ikoy',
    'container.build_id' => '71c47cb1',
    'container.build_time' => 1590079311,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOh1ikoy');
