<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8vmpyro\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8vmpyro/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8vmpyro.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8vmpyro\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8vmpyro\App_KernelDevDebugContainer([
    'container.build_hash' => '8vmpyro',
    'container.build_id' => '698b1c91',
    'container.build_time' => 1590748023,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8vmpyro');
